### ISSUE TITLE
Raising RhizomeInsertionError raises AssertionError

### ISSUE THREAD

**Issue by jonashoechst** [umr-ds/pyserval#14]
In one case were pyserval raises an RhizomeInsertionError the Error is not risen, but instead an AssertionError is risen, because of a failing type check. 

```python
Traceback (most recent call last):
  File "/serval_routing/helpers/rhizome-list.py", line 15, in <module>
    first_bundle.update()
  File "/usr/local/lib/python2.7/dist-packages/pyserval/rhizome.py", line 83, in update
    bundle_secret=self.bundle_secret
  File "/usr/local/lib/python2.7/dist-packages/pyserval/rhizome.py", line 427, in insert
    raise RhizomeInsertionError(bundle_status=bundle_status, bundle_message=bundle_message)
  File "/usr/local/lib/python2.7/dist-packages/pyserval/exceptions.py", line 157, in __init__
    assert isinstance(bundle_status, int)
AssertionError
```

Minimal working example:
```python
#!/usr/bin/env python
from pyserval.client import Client

rhizome = Client().rhizome

new_bundle = rhizome.new_bundle(
    service="file",
    name="test.file",
    payload="The quick brown fox jumps over the lazy dogs back."
)
new_bundle.update()
```

**Comment by CryptoCopter** [comment]
Fixed in fad9a755cfd4aa92482beaae3ad9db4329af837c
