### ISSUE TITLE
Error message passing fails

### ISSUE THREAD

**Issue by jonashoechst** [umr-ds/pyserval#18]
When inserting an empty manifest, the error message of serval is parsed incorrectly. (It might be different to spec as well...)

Example: 
```python
from pyserval.lowlevel.rhizome import Manifest
from pyserval.client import Client

m = Manifest()
c = Client()

c.rhizome.insert(m, bundle_secret="CAFFEE") 
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyserval/rhizome.py", line 484, in insert
    bundle_status = int(serval_reply.headers.get("Serval-Rhizome-Result-Bundle-Status-Code"))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by CryptoCopter** [comment]
fixed in 6b196c660d60e4a8e73c651ca752cbddc4056df2
